const products = [
    {
        id: 1,
        image: "./images/list/p-1.png",
        name: "Red Carpet Real Estate",
        desc: "210 Zirak Road, Canada",
        brand: "For Rent",
        price: "370",
        type: "Apartment",
    },
    {
        id: 2,
        image: "./images/list/p-2.png",
        name: "Fairmount Properties",
        desc: "5698 Zirak Road, NewYork",
        brand: "For Sale",
        price: "975",
        type: "Condos",
    },
    {
        id: 3,
        image: "./images/list/p-7.png",
        name: "The Real Estate Corner",
        desc: "5624 Mooker Market, USA",
        brand: "For Rent",
        price: "586",
        type: "Offices",
    },
    {
        id: 4,
        image: "./images/list/p-4.png",
        name: "Herringbone Realty",
        desc: "5621 Liverpool, London",
        brand: "For Sale",
        price: "750",
        type: "Homes & Villas",
    },
    {
        id: 5,
        image: "./images/list/p-5.png",
        name: "Brick Lane Realty",
        desc: "210 Montreal Road, Canada",
        brand: "For Rent",
        price: "485",
        type: "Commercial",
    },
    {
        id: 6,
        image: "./images/list/p-6.png",
        name: "Banyon Tree Realty",
        desc: "210 Zirak Road, Canada",
        brand: "For Sale",
        price: "274",
        type: "Apartment",
    },
];

module.exports = products;
